apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gold
